### ISSUE TITLE
Cannot run bf.go example

### ISSUE THREAD

**Issue by marco-hrlic** [milosgajdos83/go-estimate#3]
When I copy bf.go into my project and run it I get the following output:
```../esp/go/pkg/mod/github.com/milosgajdos83/go-estimate@v0.0.0-20190409000106-fec0aabc4d5e/noise/gaussian.go:44:32: g.dist.CovarianceMatrix(nil) used as value```
But if I run it from the examples dir it works as expected.

**Comment by antegulin** [comment]
+1

**Comment by milosgajdos83** [comment]
Hi, thanks for opening the issue.

The examples build well if built as part of the project (`make examples`) because when you run `make dep` it `vendor`s the dependencies into `vendor/` subdirectory (not tracked by `git`). 

Dependency vendoring is done using [godep](https://github.com/golang/dep) which honours the versions of the packages locked in `Gopkg.lock`, which locks the `gonum/stat` package (used in `nosie/gaussian.go`) to:

```
revision = "169ee079a3fcd6706a67702cf202192814167c28"
```
as you can see [here](https://github.com/milosgajdos83/go-estimate/blob/master/Gopkg.lock#L144)

However, if you copy over any of the examples outside the project and try to vendor them on their `master` revisions i.e. on the latest available dependencies the build will fail as you've just noticed 

The reasons is the change in `gonum/stat` package which changed the `stat/distmv/normal.go` API as can be seen [here](https://github.com/gonum/gonum/commit/5d695651a1d533b5b371458b6da17b45c17ed718#diff-cfcb495bb1c38b6148082184684f2cb1R160) vs. the locked old version [here](https://github.com/gonum/gonum/commit/5d695651a1d533b5b371458b6da17b45c17ed718#diff-cfcb495bb1c38b6148082184684f2cb1L159) which is used in `go-estimate`.

I suspect you are using `go mod`ules (based on the output of your commands) which is beta in `1.12`? 

Unfortunately `go mod` support in this library is very alpha. Clearly, it needs to be sorted to prepare for the next release of `go`.

I will have some time for this hopefully early next week to look into this, for the time being, when trying to compile the examples outside the project you will have to pin `gonum` dependency to some commit before the `169ee079a3fcd6706a67702cf202192814167c28` revision of `gonum/stat` as described earlier.

If you find some time to fix this for everyone I welcome PRs :-)

**Comment by milosgajdos83** [comment]
I have updated and cleaned up project dependencies.

Thanks again for raising an issue as it has highlighted the chaotic mess the dependency tree was in! As you can see by inspecting `go.mod` or `Gopkg.toml` they're now much leaner and cleaner.

I've tested the build using the `go mod`, so you should be able to verify it using the following steps:
* copy `bf.go` outside project directory tree
* change to the directory where you copied `bf.go`
* run `export GO111MODULE=on` to enable `go` module support
* `go mod init`
* `go build`
* profit :-)
